/**
 * This file was generated by Apache newt version: 1.8.0-dev
 */

#ifndef H_MYNEWT_LOGCFG_
#define H_MYNEWT_LOGCFG_

#include "modlog/modlog.h"
#include "log_common/log_common.h"

#define BLE_HS_LOG_DEBUG(...)    elog_d("nimble", __VA_ARGS__)
#define BLE_HS_LOG_INFO(...)     elog_i("nimble", __VA_ARGS__)
#define BLE_HS_LOG_WARN(...)     elog_w("nimble", __VA_ARGS__)
#define BLE_HS_LOG_ERROR(...)    elog_e("nimble", __VA_ARGS__)
#define BLE_HS_LOG_CRITICAL(...) elog_e("nimble", __VA_ARGS__)
#define BLE_HS_LOG_HEXDUMP(...)  elog_d_hexdump("nimble", __VA_ARGS__)
#define BLE_HS_LOG_DISABLED(...) IGNORE(__VA_ARGS__)

#define DFLT_LOG_DEBUG(...)      elog_d("nimble", __VA_ARGS__)
#define DFLT_LOG_INFO(...)       elog_i("nimble", __VA_ARGS__)
#define DFLT_LOG_WARN(...)       elog_w("nimble", __VA_ARGS__)
#define DFLT_LOG_ERROR(...)      elog_e("nimble", __VA_ARGS__)
#define DFLT_LOG_CRITICAL(...)   elog_e("nimble", __VA_ARGS__)
#define DFLT_LOG_HEXDUMP(...)    elog_d_hexdump("nimble", __VA_ARGS__)
#define DFLT_LOG_DISABLED(...)   IGNORE(__VA_ARGS__)

#define MFG_LOG_DEBUG(...)       elog_d("nimble", __VA_ARGS__)
#define MFG_LOG_INFO(...)        elog_i("nimble", __VA_ARGS__)
#define MFG_LOG_WARN(...)        elog_w("nimble", __VA_ARGS__)
#define MFG_LOG_ERROR(...)       elog_e("nimble", __VA_ARGS__)
#define MFG_LOG_CRITICAL(...)    elog_e("nimble", __VA_ARGS__)
#define MFG_LOG_HEXDUMP(...)     elog_d_hexdump("nimble", __VA_ARGS__)
#define MFG_LOG_DISABLED(...)    IGNORE(__VA_ARGS__)

#endif
