/**
 * This file was generated by Apache newt version: 1.8.0-dev
 */

#ifndef H_MYNEWT_LOGCFG_
#define H_MYNEWT_LOGCFG_

#include "modlog/modlog.h"
#include "log_common/log_common.h"

#define BLE_HS_LOG_DEBUG(...)       IGNORE(__VA_ARGS__)
#define BLE_HS_LOG_INFO(...)        log_i(__VA_ARGS__)
#define BLE_HS_LOG_WARN(...)        log_w(__VA_ARGS__)
#define BLE_HS_LOG_ERROR(...)       log_e(__VA_ARGS__)
#define BLE_HS_LOG_CRITICAL(...)    log_e(__VA_ARGS__)
#define BLE_HS_LOG_DISABLED(...)    IGNORE(__VA_ARGS__)

#define DFLT_LOG_DEBUG(...)     IGNORE(__VA_ARGS__)
#define DFLT_LOG_INFO(...)      log_i(__VA_ARGS__)
#define DFLT_LOG_WARN(...)      log_w(__VA_ARGS__)
#define DFLT_LOG_ERROR(...)     log_e(__VA_ARGS__)
#define DFLT_LOG_CRITICAL(...)  log_e(__VA_ARGS__)
#define DFLT_LOG_DISABLED(...)  IGNORE(__VA_ARGS__)

#define MFG_LOG_DEBUG(...)      IGNORE(__VA_ARGS__)
#define MFG_LOG_INFO(...)       log_i(__VA_ARGS__)
#define MFG_LOG_WARN(...)       log_w(__VA_ARGS__)
#define MFG_LOG_ERROR(...)      log_e(__VA_ARGS__)
#define MFG_LOG_CRITICAL(...)   log_e(__VA_ARGS__)
#define MFG_LOG_DISABLED(...)   IGNORE(__VA_ARGS__)

#endif
